apiVersion: batch/v1
kind: CronJob
metadata:
  name: hwpv-auto-approval
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: "30 3 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: hwpv-auto-approval
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            args:
            - node
            - start-daily-auto-approval-check
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
