apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hwpv-payment-run
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: "5 0 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: hwpv-payment-run
            image: "{{ .Values.image.repository }}:{{ .Values.generic-service.image.tag | default .Chart.AppVersion }}"
            args:
            - node
            - start-schedule-payment-run
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
