apiVersion: batch/v1
kind: CronJob
metadata:
  name: hwpv-worker-tasks
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 15
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: hwpv-worker-tasks
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            args:
            - node
            - start-worker-tasks
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
