main_branch:
  filters:
    branches:
      only: main
feature_branch:
  filters:
    branches:
      ignore: main
version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@11
parameters:
  alerts-slack-channel:
    type: string
    default: "help-with-prison-visits-alerts-nonprod"
  releases-slack-channel:
    type: string
    default: visits-releases
  node-version:
    type: string
    default: 22.20-browsers
jobs:
  unit_test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Unit Tests
          command: npm run test
# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - unit_test
#       - hmpps/helm_lint:
#           name: helm_lint
#       - hmpps/build_docker:
#           name: build_docker
#       - request_dev_approval:
#           filters:
#             branches:
#               ignore: main
#           type: approval
#           requires:
#             - helm_lint
#             - unit_test
#             - build_docker
#       - hmpps/deploy_env:
#           filters:
#             branches:
#               ignore: main
#           name: deploy_dev_preview
#           env: "dev"
#           context: hmpps-common-vars
#           requires:
#             - request_dev_approval
#       - request_preprod_approval_branch:
#           filters:
#             branches:
#               ignore: main
#           type: approval
#           requires:
#             - deploy_dev_preview
#       - hmpps/deploy_env:
#           filters:
#             branches:
#               ignore: main
#           name: deploy_preprod_preview
#           env: "preprod"
#           context: help-with-prison-visits-internal-preprod
#           requires:
#             - request_preprod_approval_branch
#       - hmpps/deploy_env:
#           filters:
#             branches:
#               only: main
#           name: deploy_dev
#           env: "dev"
#           context: hmpps-common-vars
#           requires:
#             - helm_lint
#             - unit_test
#             - build_docker
#       - request_preprod_approval:
#           filters:
#             branches:
#               only: main
#           type: approval
#           requires:
#             - deploy_dev
#       - hmpps/deploy_env:
#           name: deploy_preprod
#           env: "preprod"
#           context: help-with-prison-visits-asynchronous-worker-preprod
#           requires:
#             - request_preprod_approval
#       - request_prod_approval:
#           type: approval
#           requires:
#             - deploy_preprod
#       - hmpps/deploy_env:
#           name: deploy_prod
#           env: "prod"
#           slack_notification: true
#           slack_channel_name: << pipeline.parameters.releases-slack-channel >>
#           context:
#             - help-with-prison-visits-asynchronous-worker-prod
#             - hmpps-common-vars
#           requires:
#             - request_prod_approval
