module.exports = {
  NEW: 'NEW',
  PENDING: 'PENDING',
  REQUEST_INFORMATION: 'REQUEST-INFORMATION',
  UPDATED: 'UPDATED',
  INPROGRESS: 'IN-PROGRESS',
  SUBMITTED: 'SUBMITTED',
  COMPLETE: 'COMPLETE',
  FAILED: 'FAILED',
  AUTOAPPROVED: 'AUTO-APPROVED',
  APPROVED: 'APPROVED',
  REQUEST_INFO_PAYMENT: 'REQUEST-INFO-PAYMENT',
  REJECTED: 'REJECTED',
}
