module.exports = {
  ACCEPT_CLAIM_NOTIFICATION: 'ACCEPT-CLAIM-NOTIFICATION',
  REJECT_CLAIM_NOTIFICATION: 'REJECT-CLAIM-NOTIFICATION',
  REQUEST_INFORMATION_CLAIM_NOTIFICATION: 'REQUEST-INFORMATION-CLAIM-NOTIFICATION',
  REQUEST_INFORMATION_RESPONSE_SUBMITTED_NOTIFICATION: 'REQUEST-INFORMATION-RESPONSE-SUBMITTED-NOTIFICATION',
  ADVANCE_CLAIM_EVIDENCE_REMINDER_NOTIFICATION: 'ADVANCE-CLAIM-EVIDENCE-REMINDER-NOTIFICATION',
  GENERATE_DIRECT_PAYMENTS: 'GENERATE-DIRECT-PAYMENTS',
  CLEANUP_OLD_PAYMENT_FILES: 'CLEANUP-OLD-PAYMENT-FILES',
  SEND_CLAIM_NOTIFICATION: 'SEND-CLAIM-NOTIFICATION',
  COMPLETE_CLAIM: 'COMPLETE-CLAIM',
  REQUEST_INFORMATION_RESPONSE: 'REQUEST-INFORMATION-RESPONSE',
  DWP_CHECK: 'DWP-CHECK',
  SEND_PERFORMANCE_PLATFORM_METRICS_FOR_DAY: 'SEND-PERFORMANCE-PLATFORM-METRICS-FOR-DAY',
  SEND_ALL_ADVANCE_CLAIM_REMINDERS_FOR_DAY: 'SEND_ALL_ADVANCE_CLAIM_REMINDERS_FOR_DAY',
  MARK_ALL_OVERPAYMENTS: 'MARK_ALL_OVERPAYMENTS',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
  CLEANUP_OLD_ELIGIBILITY_DATA: 'CLEANUP_OLD_ELIGIBILITY_DATA'
}
