module.exports = {
  ACCEPT_CLAIM_NOTIFICATION: 'ACCEPT-CLAIM-NOTIFICATION',
  REJECT_CLAIM_NOTIFICATION: 'REJECT-CLAIM-NOTIFICATION',
  FIRST_TIME_CLAIM_NOTIFICATION: 'FIRST-TIME-CLAIM-NOTIFICATION'
}
