module.exports = {
  ACCEPT_CLAIM_NOTIFICATION: 'ACCEPT-CLAIM-NOTIFICATION',
  REJECT_CLAIM_NOTIFICATION: 'REJECT-CLAIM-NOTIFICATION',
  REQUEST_INFORMATION_CLAIM_NOTIFICATION: 'REQUEST-INFORMATION-CLAIM-NOTIFICATION',
  REQUEST_INFORMATION_RESPONSE_SUBMITTED_NOTIFICATION: 'REQUEST-INFORMATION-RESPONSE-SUBMITTED-NOTIFICATION',
  ADVANCE_CLAIM_EVIDENCE_REMINDER_NOTIFICATION: 'ADVANCE-CLAIM-EVIDENCE-REMINDER-NOTIFICATION',
  SEND_CLAIM_NOTIFICATION: 'SEND-CLAIM-NOTIFICATION',
  COMPLETE_CLAIM: 'COMPLETE-CLAIM',
  REQUEST_INFORMATION_RESPONSE: 'REQUEST-INFORMATION-RESPONSE',
  DWP_CHECK: 'DWP-CHECK',
  SEND_MALWARE_ALERT: 'SEND-MALWARE-ALERT',
  ARCHIVE_OLD_CLAIMS: 'ARCHIVE-OLD-CLAIMS',
  ARCHIVE_CLAIM: 'ARCHIVE-CLAIM',
  REFERENCE_RECOVERY: 'REFERENCE_RECOVERY',
  DWP_FAILED_NOTIFICATION: 'DWP-FAILED-NOTIFICATION',
  AUTO_APPROVE_CLAIMS: 'AUTO-APPROVE-CLAIMS',
  SEND_REQUEST_INFORMATION_REMINDER_NOTIFICATION: 'SEND-REQUEST-INFORMATION-REMINDER-NOTIFICATION'
}
