apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: help-with-prison-visits-asynchronous-worker
version: 0.3.0

dependencies:
  - name: generic-prometheus-alerts
    version: 1.11.7
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
