---
# Values here are the same across all environments
nameOverride: help-with-prison-visits-asynchronous-worker

image:
  repository: quay.io/hmpps/help-with-prison-visits-asynchronous-worker
  tag: app_version    # override at deployment time
  port: 3999

env:
  PAYOUT_SFTP_HOST: "37.152.49.212"
  PAYOUT_SFTP_PORT: "52317"
  BASIC_AUTH_ENABLED: "false"
  APVS_PERFORMANCE_PLATFORM_URL: "https://www.performance.service.gov.uk/data/assisted-prison-visits/transactions-by-channel"
  APVS_NOTIFY_API_URL: https://api.notifications.service.gov.uk
  APVS_FILE_TMP_DIR: '/app/tmp'
  APVS_NOTIFY_ACCEPTED_CLAIM_ADVANCE_BANK_EMAIL_TEMPLATE_ID: d0ccc069-01a6-4cc3-b1f0-ee4cbec4d652
  APVS_NOTIFY_ACCEPTED_CLAIM_ADVANCE_PAYOUT_EMAIL_TEMPLATE_ID: 2dd232f8-3977-4d34-8296-b5bad6fa7d61
  APVS_NOTIFY_ACCEPTED_CLAIM_BANK_EMAIL_TEMPLATE_ID: 4c34eb1e-1449-4ae9-b5f1-05e317388d98
  APVS_NOTIFY_ACCEPTED_CLAIM_MANUAL_EMAIL_TEMPLATE_ID: 73ee742e-6e9b-433d-a406-246405fd9c3e
  APVS_NOTIFY_ACCEPTED_CLAIM_PAYOUT_EMAIL_TEMPLATE_ID: ed7eccf8-5623-482a-93e2-d78e4acebe73
  APVS_NOTIFY_ADVANCE_CLAIM_EVIDENCE_REMINDER_TEMPLATE_ID: b6de4d5e-9bbf-43b2-8b16-a3a3e3f3007e
  APVS_NOTIFY_ADVANCE_CLAIM_SECOND_EVIDENCE_REMINDER_TEMPLATE_ID: 0ffe86ba-608c-4cde-ad0a-9ec8f0e45a81
  APVS_NOTIFY_MALWARE_UPLOAD_EMAIL_TEMPLATE_ID: 0c5d8ccc-cc04-4789-bac7-467c4714af4a
  APVS_NOTIFY_REJECTED_CLAIM_EMAIL_TEMPLATE_ID: daade7c1-ad2e-47c1-bd7a-7a79b115b995
  APVS_NOTIFY_REQUEST_INFORMATION_CLAIM_EMAIL_TEMPLATE_ID: 72a3ee72-321a-4470-9db1-e05811364a86
  APVS_NOTIFY_REQUEST_INFORMATION_REMINDER_EMAIL_TEMPLATE_ID: 7a465799-0b93-4ff9-9952-0ac73de01344
  APVS_NOTIFY_REQUEST_INFORMATION_RESPONSE_SUBMITTED_EMAIL_TEMPLATE_ID: 5dd77ed5-5c16-4c70-afb5-9b4f999b88f3
  APVS_NOTIFY_SEND_REFERENCE_RECOVERY_EMAIL_TEMPLATE_ID: b647aca3-03c1-497d-9d92-997d8dd49aa1
  APVS_NOTIFY_SUBMIT_CLAIM_EMAIL_TEMPLATE_ID: 508b23b3-3f1c-45c2-bdc7-db90e3fae8b0
  APVS_NOTIFY_UPDATE_CONTACT_DETAILS_EMAIL_TEMPLATE_ID: b4478243-1120-4fc3-8cab-a8a512868254
  LOGGING_LEVEL: DEBUG

# Pre-existing kubernetes secrets to load as environment variables in the deployment.
# namespace_secrets:
#   [name of kubernetes secret]:
#     [name of environment variable as seen by app]: [key of kubernetes secret to load]

namespace_secrets:
  help-with-prison-visits-asynchronous-worker:
    APVS_DATABASE: "APVS_DATABASE"
    APVS_ASYNC_WORKER_USERNAME: "APVS_ASYNC_WORKER_USERNAME"
    APVS_ASYNC_WORKER_PASSWORD: "APVS_ASYNC_WORKER_PASSWORD"
    APPINSIGHTS_INSTRUMENTATIONKEY: "APVS_APP_INSIGHTS_INSTRUMENTATION_KEY"
    APVS_NOTIFY_API_KEY: "APVS_NOTIFY_API_KEY"
    APVS_NOTIFY_CLIENT_ID: "APVS_NOTIFY_CLIENT_ID"
    PAYOUT_SFTP_USER: "PAYOUT_SFTP_USER"
    PAYOUT_SFTP_PASSWORD: "PAYOUT_SFTP_PASSWORD"
    APVS_DISTANCE_CALCULATION_DIRECTIONS_API_KEY: "APVS_DISTANCE_CALCULATION_DIRECTIONS_API_KEY"
    APVS_DWP_BENEFIT_CHECKER_CLIENTORGID: "APVS_DWP_BENEFIT_CHECKER_CLIENTORGID"
    APVS_DWP_BENEFIT_CHECKER_CLIENTREFERENCE: "APVS_DWP_BENEFIT_CHECKER_CLIENTREFERENCE"
    APVS_DWP_BENEFIT_CHECKER_CLIENTUSERID: "APVS_DWP_BENEFIT_CHECKER_CLIENTUSERID"
    APVS_DWP_BENEFIT_CHECKER_LSCSERVICENAME: "APVS_DWP_BENEFIT_CHECKER_LSCSERVICENAME"
  rds-sqlserver-instance-output:
    APVS_DATABASE_SERVER: 'rds_instance_address'
  hwpv-document-s3-internal:
    AWS_ACCESS_KEY_ID: access_key_id
    AWS_SECRET_ACCESS_KEY: secret_access_key
    AWS_S3_BUCKET_NAME: bucket_name

generic-prometheus-alerts:
  targetApplication: help-with-prison-visits-asynchronous-worker
  jobTargetOverride: ".*"
  cronjobTargetOverride: ".*"
