---
# Environment specific values, override helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml
replicaCount: 2

env:
  APVS_DWP_BENEFIT_CHECKER_ENABLED: "true"
  APVS_DWP_BENEFIT_CHECKER_URL: "https://benefitchecker.legalservices.gov.uk/lsx/lsc-services/benefitChecker"
  APVS_ZENDESK_ENABLED: "true"
  APVS_ZENDESK_API_URL: "https://ministryofjustice.zendesk.com"
  APVS_ZENDESK_PROD_ENVIRONMENT: "true"
  APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits.service.gov.uk'
  PAYOUT_SFTP_ENABLED: "true"
  PAYOUT_SFTP_REMOTE_PATH: "data/"
  APVS_ARCHIVE_CLAIMS_AFTER_DAYS: '700'
  APVS_PAYOUT_FILENAME_PREFIX: 'DF_SANTANDERNOMS086_LETTER_'

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits
